BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "SCHEDULE_TABLE" (
	"STUDENT_ID"	INTEGER,
	"CRN"	INTEGER,
	FOREIGN KEY("CRN") REFERENCES "CLASS"("CRN") ON DELETE CASCADE,
	FOREIGN KEY("STUDENT_ID") REFERENCES "STUDENT"("STUDENT_ID") ON DELETE CASCADE,
	PRIMARY KEY("STUDENT_ID","CRN")
);
CREATE TABLE IF NOT EXISTS "STUDENT" (
	"STUDENT_ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"LASTNAME"	TEXT,
	"FIRSTNAME"	TEXT,
	"ADDRESS"	TEXT,
	"MAJOR"	TEXT
);
CREATE TABLE IF NOT EXISTS "CLASS" (
	"CRN"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"COURSE_NAME"	TEXT
);
INSERT INTO "SCHEDULE_TABLE" VALUES (1,1);
INSERT INTO "SCHEDULE_TABLE" VALUES (1,2);
INSERT INTO "SCHEDULE_TABLE" VALUES (2,3);
INSERT INTO "SCHEDULE_TABLE" VALUES (2,5);
INSERT INTO "SCHEDULE_TABLE" VALUES (1,4);
INSERT INTO "SCHEDULE_TABLE" VALUES (2,4);
INSERT INTO "SCHEDULE_TABLE" VALUES (3,3);
INSERT INTO "SCHEDULE_TABLE" VALUES (4,1);
INSERT INTO "STUDENT" VALUES (1,'Doe','John','2 Lane','Chemistry');
INSERT INTO "STUDENT" VALUES (2,'Body','Alpha','3 Road','Computer Science');
INSERT INTO "STUDENT" VALUES (3,'Doe','Jane','9 Drive','Geography');
INSERT INTO "STUDENT" VALUES (4,'Suraj','Karan','10 Out of Ten','Biomedical Engineering');
INSERT INTO "CLASS" VALUES (1,'Algorithms');
INSERT INTO "CLASS" VALUES (2,'Data Structures');
INSERT INTO "CLASS" VALUES (3,'Organic Chemistry');
INSERT INTO "CLASS" VALUES (4,'General Chemistry');
INSERT INTO "CLASS" VALUES (5,'Physical Chemistry');
COMMIT;
