BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "SCHEDULE_TABLE" (
	"STUDENT_ID"	INTEGER,
	"CRN"	INTEGER,
	FOREIGN KEY("CRN") REFERENCES "CLASS"("CRN") ON DELETE CASCADE,
	FOREIGN KEY("STUDENT_ID") REFERENCES "STUDENT"("STUDENT_ID") ON DELETE CASCADE,
	PRIMARY KEY("STUDENT_ID","CRN")
);
CREATE TABLE IF NOT EXISTS "STUDENT" (
	"STUDENT_ID"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"LASTNAME"	TEXT,
	"FIRSTNAME"	TEXT,
	"ADDRESS"	TEXT,
	"MAJOR"	TEXT
);
CREATE TABLE IF NOT EXISTS "CLASS" (
	"CRN"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"COURSE_NAME"	TEXT
);
COMMIT;
